---
- name: "Example playbook for switches and routers"
  hosts: routers
  gather_facts: false
  connection: network_cli
  vars:
    cli:
      username: miggy
      password: one23
      timeout: 100
  tasks:
    - name: "testing sending commands"
      cisco.ios.ios_command:  
        commands:
          - show version
          - show ip int brief

      register: print_output


