- name: "Rollback Cisco Routers and Switches"
  hosts: all
  gather_facts: false
  tasks:
  - name: "Push config file"
    cisco.ios.ios_config:
      src: #missing the config file

  - name: "Saving the configuration"
    cisco.ios.ios_config:
      save_when: modified
