- name: Get the power state of the IP Power 9258 unit
  hosts: ippower
  gather_facts: false
  tasks:
  - name: Get the state of all of the ports
    uri:
      url: "http://{{ inventory_hostname }}/Set.cmd?CMD=GetPower"
      user: "{{ ippower_user }}"
      password: "{{ ippower_pass }}"
      return_content: yes
    register: output
    delegate_to: localhost

  - name: Creating dictionary from the output
    set_fact:
      result: "{{ result | default({},true) | combine( { key: value } ) }}"
    loop: "{{ output.content.split(',') }}"
    loop_control:
      index_var: outlet_index
    vars:
      key: "port{{ outlet_index+1 }}"
      value: "{{item | regex_replace('(.*)=','') | replace('0','Off') | regex_search('Off') | default('On', true) }}"

  - name: Show the Parsed Output
    debug: var=result

