- name: Push new configuration
  hosts: switches
  gather_facts: false
  connection: network_cli
  tasks:
  - name: Wait for SSH to be available on the device
    wait_for:
      host: "{{ inventory_hostname }}"
      port: 22
      state: started
      delay: 15
      timeout: 120
    when: "'switches' in group_names"

  - name: Push config file to switchTwo
    ios_config:
      src: "{{ config_file_switchTwo }}"
    when: "inventory_hostname == '192.168.1.3'"

  - name: Push config file to the switchThree
    ios_config:
      src: "{{ config_file_switchThree }}"
    when: "inventory_hostname == '192.168.1.4'"

  - name: Getting router/switch information
    cisco.ios.ios_command:
      commands:
      - show version
      - show ip int brief
      - show run
    register: print_info

