- name: Configure router and switch sequentially
  hosts: all
  gather_facts: false
  connection: network_cli
  tasks:
  - name: Save running config locally
    cisco.ios.ios_command:
      commands:
      - "Copy running-config flash:/last-backup.txt"
      prompts:
      - "[confirm]"
      response:
      - "\n"
    when: "'routers' in group_names or 'switches' in group_names"

  - name: Reload the device
    cisco.ios.ios_reboot:
      confirm: yes
      save_when: never
    when: "'routers' in group_names or 'switches' in group_names"

  - name: Wait for SSH to be available on the router
    wait_for:
      host: "192.168.1.1"
      port: 22
      state: started
      delay: 15
      timeout: 120
    when: "'routers' in group_names"

  - name: Push config file to the router
    ios_config:
      src: "{{ config_file }}"
    when: "'routers' in group_names and inventory_hostname == '192.168.1.1'"

  # - name: Wait for ports to come up on the router
  #   pause:
  #     minutes: 0.5
  #   when: "'routers' in group_names and inventory_hostname == '10.95.1.169'"

  - name: Wait for SSH to be available on the switch
    wait_for:
      host: "192.168.1.2"
      port: 22
      state: started
      delay: 15
      timeout: 120
    when: "'switches' in group_names"

  - name: Push config file to the switch
    ios_config:
      src: "{{ config_file }}"
    when: "'switches' in group_names and inventory_hostname == '192.168.1.2'"

  - name: Getting router/switch information
    cisco.ios.ios_command:
      commands:
      - show version
      - show ip int brief
    register: print_info
